language: python

cache: pip

matrix:
  include:
    - python: "2.7"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      env: COVERAGE=true
    - python: "3.8"

install:
  - pip install -r pip-requirements-dev.txt
  - pip list
  - if [[ $COVERAGE == true ]]; then pip install codeclimate-test-reporter; fi
  - if [[ $COVERAGE == true ]]; then pip install coveralls; fi
  # Build in place so we can run tests
  - python setup.py build_ext --inplace

script: 
  - py.test numina
  - if [[ $COVERAGE == true ]]; then coverage run --source numina -m py.test; fi

after_success:
  - if [[ $COVERAGE == true ]]; then coveralls; fi
  - if [[ $COVERAGE == true ]]; then codeclimate-test-reporter; fi

