version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install numpy scipy astropy pytest python-dateutil matplotlib six PyYaml
      - run:
          command: |
            . venv/bin/activate
            py.test numina
