name: Build wheel
on:
  workflow_dispatch

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'
          
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.5 
      
      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_SKIP: pp*

          
      - uses: actions/upload-artifact@v2
        with:
          name: numina-wheels
          path: ./wheelhouse/*.whl
        
